version: '3'
services:
    store:
        build:
            context: ../schani_store
    uploader:
        build:
            context: ../schani_uploader
    userinfo:
        build:
            context: ../schani_userinfo
