version: '3'
services:
    import:
        build:
            context: ../schani_import
    processor:
        build:
            context: ../schani_processor
    store:
        build:
            context: ../schani_store
    uploader:
        build:
            context: ../schani_uploader
    userinfo:
        build:
            context: ../schani_userinfo
