version: '3'
services:
    import:
        build:
            context: ../schani_import
        ports:
            - "8100:8000"
    processor:
        build:
            context: ../schani_processor
        ports:
            - "8101:8000"
    store:
        build:
            context: ../schani_store
        ports:
            - "8102:8000"
    uploader:
        build:
            context: ../schani_uploader
        ports:
            - "8103:8000"
    userinfo:
        build:
            context: ../schani_userinfo
        ports:
            - "8104:8000"
