version: '3'
services:
    apigateway:
        image: schanirs/apigateway
        ports:
            - "8000:3000"
        links:
            - auth
            - import
            - library
            - store

    auth:
        image: schanirs/auth
        ports:
            - "8001:8000"

    import:
        image: schanirs/import
        environment:
            - "AMQP_ADDRESS=processing_queue"
            - "DATABASE_URL=postgres://import:BSStykoth4XneRoAguZx@import_db:5432/schani_import"
        ports:
            - "8002:8000"
        links:
            - import_db
            - library
            - processing_queue
            - store
    import_db:
        image: postgres
        environment:
            - "POSTGRES_USER=import"
            - "POSTGRES_PASSWORD=BSStykoth4XneRoAguZx"
            - "POSTGRES_DB=schani_import"

    library:
        image: schanirs/library
        environment:
            - "DATABASE_URL=postgres://library:474FZLnQsRvQ4uzsoJ2JpTTi3WeYA5BP@library_db:5432/schani_library"
        ports:
            - "8003:8000"
        links:
            - library_db
    library_db:
        image: postgres
        environment:
            - "POSTGRES_USER=library"
            - "POSTGRES_PASSWORD=474FZLnQsRvQ4uzsoJ2JpTTi3WeYA5BP"
            - "POSTGRES_DB=schani_library"

    processing_queue:
        image: rabbitmq:3-management
        ports:
            - "8100:15672" #mgmt
        volumes:
            - processing_queue_storage:/var/lib/rabbitmq
    processor:
        image: schanirs/processor
        links:
            - library
            - processing_queue
            - store

    store:
        image: schanirs/store
        environment:
            - "ROCKET_ADDRESS=0.0.0.0"
            - "STORAGE_HOST=http://store_s3:9000"
            - "MINIO_ACCESS_KEY=CMDBEHZNRIW1UA6AQ80W"
            - "MINIO_SECRET_KEY=9Wh/pknTtRVTzwyBo3HCdCXVYusegHWcBjT4g6cR"
            - "AWS_ACCESS_KEY_ID=CMDBEHZNRIW1UA6AQ80W"
            - "AWS_SECRET_ACCESS_KEY=9Wh/pknTtRVTzwyBo3HCdCXVYusegHWcBjT4g6cR"
        ports:
            - "8004:8000"
        links:
            - store_s3
    store_s3:
        image: minio/minio
        environment:
            - "MINIO_ACCESS_KEY=CMDBEHZNRIW1UA6AQ80W"
            - "MINIO_SECRET_KEY=9Wh/pknTtRVTzwyBo3HCdCXVYusegHWcBjT4g6cR"
        command: server /data
        volumes:
            - store_storage:/data

volumes:
    processing_queue_storage:
    store_storage:
