version: '3'
services:
    import:
        links:
            - import_db
            - processing_amqp
        environment:
            - "ROCKET_PORT=8000"
            - "ROCKET_ADDRESS=0.0.0.0"
            - "DATABASE_URL=postgres://import:xkQBx7EVgr@userinfo_db/import"
    import_db:
        image: postgres
        environment:
            - "POSTGRES_USER=import"
            - "POSTGRES_PASSWORD=xkQBx7EVgr"
            - "POSTGRES_DB=import"
    processor:
        links:
            - processing_amqp
    processing_amqp:
        image: rabbitmq
    store:
        links:
            - store_db
        environment:
            - "ROCKET_PORT=8000"
            - "ROCKET_ADDRESS=0.0.0.0"
            - "DATABASE_URL=postgres://store:HchqJkF2Qe@userinfo_db/store"
    store_db:
        image: postgres
        environment:
            - "POSTGRES_USER=store"
            - "POSTGRES_PASSWORD=HchqJkF2Qe"
            - "POSTGRES_DB=store"
    uploader:
        environment:
            - "ROCKET_PORT=8000"
            - "ROCKET_ADDRESS=0.0.0.0"
    userinfo:
        links:
            - userinfo_db
        environment:
            - "ROCKET_PORT=8000"
            - "ROCKET_ADDRESS=0.0.0.0"
            - "DATABASE_URL=postgres://userinfo:fTAqg9Hxmo@userinfo_db/userinfo"
    userinfo_db:
        image: postgres
        environment:
            - "POSTGRES_USER=userinfo"
            - "POSTGRES_PASSWORD=fTAqg9Hxmo"
            - "POSTGRES_DB=userinfo"
